# Basic Information 
title: Qiyao Pan
position: Ph.D. Candidate
affiliation: The Graduate Center, City University of New York
email: qpan@gradcenter.cuny.edu

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Qiyao Pan
description: The academic website page
canonical: https://qiyao-pan.github.io/

# Links 
# If you don't need one of them, you may delete the corresponding line.
cv_link: assets/files/curriculum_vitae.pdf
twitter: https://x.com/qpangc
linkedin: https://www.linkedin.com/in/qiyao-pan
github_link: https://github.com/qiyao-pan

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: false

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: false

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
